spring:
  application:
    name: native

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/native_database
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
