CREATE OR REPLACE SEQUENCE quote_seq START WITH 1 INCREMENT BY 50 NOCACHE;

CREATE TABLE IF NOT EXISTS quote (
    id BIGINT NOT NULL,
    message VARCHAR(255),
    CONSTRAINT quote_message UNIQUE (message),
    PRIMARY KEY (id)
) ENGINE=InnoDB;
